language: php
sudo: false
dist: trusty

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: COVERAGE=0
    - php: 7.2
      env: COVERAGE=1

before_install:
  - travis_retry composer self-update

before_script:
  - travis_retry composer install --no-interaction --prefer-source
  - phpenv rehash
  - set +H

script:
  - vendor/bin/phpunit
  - if [[ $COVERAGE = '1' ]]; then composer complete-check; fi
  - if [[ $COVERAGE = '1' ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=clover.xml; fi

after_script:
  - if [[ $COVERAGE = '1' ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
